language: c
env:
  - OCAML_VERSION=4.08.0 IS593_OPAM_SWITCH=is593-${OCAML_VERSION} LLVM_VERSION=9
os:
  - linux
dist: bionic
cache:
  directories:
    - ${HOME}/.opam
before_install:
  - export OPAMYES=1
  - sudo add-apt-repository -y ppa:avsm/ppa
  - sudo apt update
  - sudo apt install -y opam
  - sudo apt install -y llvm-${LLVM_VERSION}-dev libllvm-${LLVM_VERSION}-ocaml-dev clang-${LLVM_VERSION}
  - sudo update-alternatives --install /usr/lib/llvm llvm /usr/lib/llvm-${LLVM_VERSION} 20 --slave /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-${LLVM_VERSION}
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${LLVM_VERSION} 10
  - opam init --compiler=${OCAML_VERSION} --disable-sandboxing
  - opam switch ${IS593_OPAM_SWITCH} || opam switch create ${IS593_OPAM_SWITCH} ${OCAML_VERSION}
  - eval $(opam env)
install:
  - opam install dune ounit llvm.9.0.0
script:
  - make test
